fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    eyplib: "git://github.com/NTTCom-MS/eyp-eyplib.git"
    logrotate: "git://github.com/NTTCom-MS/eyp-logrotate.git"
  symlinks:
    iptables: "#{source_dir}"
